spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/simplebank
    username: mysql
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
